name: Publish Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'  # 버전 태그 푸시 시 실행되도록

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Get version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with:
          path: 'packages/plugin/plugin.json'
          prop_path: 'Version'
      - run: echo 'VERSION=${{ steps.version.outputs.prop }}'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build -w flow-launcher-chzzk

      - name: Prepare package directory
        run: |
          mkdir plugin
          npm pack --workspace flow-launcher-chzzk
          tar -xzf flow-launcher-chzzk-*.tgz -C plugin --strip-components=1
          cp README.md plugin/ || true

      - name: Zip plugin
        run: |
          cd plugin
          zip -r ../plugin.zip .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release v${{ steps.version.outputs.prop }}
          tag_name: v${{ steps.version.outputs.prop }}
          files: plugin.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
